### ISSUE TITLE
Power Consumption

### ISSUE THREAD

**Issue by SergioBenitez** [vsergeev/teatimer#1]
Power consumption seems a bit high at ~100mA @ 1.5V. I'm curious: do you have a more detailed breakdown of the power consumption across components?

**Comment by vsergeev** [comment]
It's like 75% due to LEDs and 25% due to loss by the boost converter. Unfortunately, to get the LEDs bright enough, they needed more current than initially projected and the boost converter is operating at relatively poor efficiency (75%).
